package com.ireum.ytdl.database.viewmodel

import android.annotation.SuppressLint
import android.app.Application
import android.content.ClipboardManager
import android.content.Context
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteDatabase.OPEN_READONLY
import android.util.Log
import android.webkit.CookieManager
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.LiveData
import androidx.lifecycle.asLiveData
import androidx.lifecycle.viewModelScope
import com.ireum.ytdl.BuildConfig
import com.ireum.ytdl.database.DBManager
import com.ireum.ytdl.database.cookies.CookieProjectionCoordinator
import com.ireum.ytdl.database.dao.CookieDao
import com.ireum.ytdl.database.models.CookieItem
import com.ireum.ytdl.database.repository.CookieRepository
import com.ireum.ytdl.ui.more.cookies.WebViewActivity
import com.ireum.ytdl.util.FileUtil
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import java.io.File
import java.util.Date
import java.util.UUID


class CookieViewModel private constructor(
    private val application: Application,
    private val repository: CookieRepository,
    private val projectionContext: Context,
) : AndroidViewModel(application) {
    constructor(application: Application) : this(
        application,
        CookieRepository(DBManager.getInstance(application).cookieDao),
        application,
    )

    internal constructor(
        application: Application,
        cookieDao: CookieDao,
        projectionContext: Context,
    ) : this(application, CookieRepository(cookieDao), projectionContext)

    val items: LiveData<List<CookieItem>> = repository.items.asLiveData()

    val cookieHeader =
            "# Netscape HTTP Cookie File\n" +
            "# WebView Generated by the YTDLnisx app\n" +
            "# This is a generated file! Do not edit."

    private val projection = arrayOf(
        CookieObject.HOST,
        CookieObject.EXPIRY,
        CookieObject.PATH,
        CookieObject.NAME,
        CookieObject.VALUE,
        CookieObject.SECURE
    )

    fun getAll(): List<CookieItem> {
        return repository.getAll()
    }

    private fun getByURL(url: String) : CookieItem? {
        return repository.getByURL(url)
    }

    private fun getByURLDescription(url: String, description: String): CookieItem? {
        return repository.getByURLDescription(url, description)
    }

    internal suspend fun acquireAndProject(
        url: String,
        description: String,
        content: String,
        requestId: String,
    ): CookieProjectionCoordinator.AcquisitionOutcome =
        CookieProjectionCoordinator.acquireAndProject(
            context = projectionContext,
            cookieHeader = cookieHeader,
            requestId = requestId,
            upsert = {
                val existing = getByURLDescription(url, description)
                if (existing != null) {
                    existing.content = content
                    existing.enabled = true
                    repository.update(existing)
                    existing.id
                } else {
                    repository.insert(
                        CookieItem(
                            id = 0,
                            url = url,
                            content = content,
                            description = description,
                            enabled = true,
                        ),
                    )
                }
            },
            readExactRow = { id ->
                getByURLDescription(url, description)?.takeIf {
                    it.id == id && it.url == url && it.description == description &&
                        it.content == content && it.enabled
                }
            },
            readEnabledRows = repository::getAllEnabled,
        )

    internal suspend fun delete(item: CookieItem): CookieProjectionCoordinator.Outcome =
        CookieProjectionCoordinator.mutateAndProject(
            projectionContext,
            cookieHeader,
            mutation = { repository.delete(item) },
            readEnabledRows = repository::getAllEnabled,
        )

    internal suspend fun changeCookieEnabledState(
        itemId: Long,
        isEnabled: Boolean,
    ): CookieProjectionCoordinator.Outcome = CookieProjectionCoordinator.mutateAndProject(
        projectionContext,
        cookieHeader,
        mutation = { repository.changeCookieEnabledState(itemId, isEnabled) },
        readEnabledRows = repository::getAllEnabled,
    )

    internal suspend fun deleteAll(): CookieProjectionCoordinator.Outcome =
        CookieProjectionCoordinator.mutateAndProject(
            projectionContext,
            cookieHeader,
            mutation = { repository.deleteAll() },
            readEnabledRows = repository::getAllEnabled,
        )

    internal suspend fun update(item: CookieItem): CookieProjectionCoordinator.Outcome =
        CookieProjectionCoordinator.mutateAndProject(
        projectionContext,
            cookieHeader,
            mutation = { repository.update(item) },
            readEnabledRows = repository::getAllEnabled,
        )

    object CookieObject {
        const val NAME = "name"
        const val VALUE = "value"
        const val SECURE = "is_secure"
        const val EXPIRY = "expires_utc"
        const val HOST = "host_key"
        const val PATH = "path"
    }

    @SuppressLint("SdCardPath")
    fun getCookiesFromDB(url: String) : Result<String> = kotlin.runCatching {
        CookieManager.getInstance().run {
            if (!hasCookies()) throw Exception("There is no cookies in the database!")
            flush()
        }
        val dbPath = File("/data/data/${BuildConfig.APPLICATION_ID}/").walkTopDown().find { it.name == "Cookies" }
            ?: throw Exception("Cookies File not found!")

        val cookieList = mutableListOf<WebViewActivity.CookieItem>()
        val db = SQLiteDatabase.openDatabase(dbPath.absolutePath, null, OPEN_READONLY)
        try {
            db.query("cookies", projection, null, null, null, null, null).use { cursor ->
                while (cursor.moveToNext()) {
                    val expiry = cursor.getLong(cursor.getColumnIndexOrThrow(CookieObject.EXPIRY))
                    val name = cursor.getString(cursor.getColumnIndexOrThrow(CookieObject.NAME))
                        ?: throw IllegalStateException("Cookie name is missing")
                    val value = cursor.getString(cursor.getColumnIndexOrThrow(CookieObject.VALUE))
                        ?: throw IllegalStateException("Cookie value is missing")
                    val path = cursor.getString(cursor.getColumnIndexOrThrow(CookieObject.PATH))
                        ?: throw IllegalStateException("Cookie path is missing")
                    val secure = cursor.getLong(cursor.getColumnIndexOrThrow(CookieObject.SECURE)) == 1L
                    val hostKey = cursor.getString(cursor.getColumnIndexOrThrow(CookieObject.HOST))
                        ?.takeIf(String::isNotBlank)
                        ?: throw IllegalStateException("Cookie host is missing")

                    val host = if (!hostKey.startsWith('.')) ".$hostKey" else hostKey
                    cookieList.add(
                        WebViewActivity.CookieItem(
                            domain = host,
                            name = name,
                            value = value,
                            path = path,
                            secure = secure,
                            expiry = expiry,
                        ),
                    )
                }
            }
        } finally {
            db.close()
        }
        if (cookieList.isEmpty()) throw IllegalStateException("WebView returned no cookie records")

        "# $url\n" +
        "# Generated by YTDLnisx\n" +
        cookieList.fold(StringBuilder("")) { acc, cookie ->
            acc.append(cookie.toNetscapeFormat()).append("\n")
        }.toString()
    }

    internal suspend fun updateCookiesFile(): CookieProjectionCoordinator.Outcome =
        CookieProjectionCoordinator.projectCurrent(
            context = projectionContext,
            cookieHeader = cookieHeader,
            readEnabledRows = repository::getAllEnabled,
        )

    suspend fun importFromClipboard() {
        try{
            val clipboard: ClipboardManager =
                application.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
            var clip = clipboard.primaryClip!!.getItemAt(0).text
            Log.e("Aaa", clip.toString())

            if (clip.startsWith("# Netscape HTTP Cookie File")){
                clip = clip.removePrefix(cookieHeader)
                val cookie = CookieItem(
                    0,
                    "",
                    clip.toString(),
                    "Cookie Import at [${Date()}]",
                    true
                )
                acquireAndProject(
                    url = cookie.url,
                    description = cookie.description,
                    content = cookie.content,
                    requestId = UUID.randomUUID().toString(),
                )
            }
        }catch (e: Exception){
            e.printStackTrace()
        }
    }

    fun exportToClipboard() = viewModelScope.launch(Dispatchers.IO) {
        try{
            val projection = updateCookiesFile()
            if (projection !is CookieProjectionCoordinator.Outcome.Ready) return@launch
            val clipboard: ClipboardManager =
                application.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
            val cookieFile = CookieProjectionCoordinator.requireUsableFile(projectionContext)
            clipboard.setText(cookieFile.readText(Charsets.UTF_8))

        }catch (e: Exception){
            e.printStackTrace()
        }
    }

    fun exportToFile(exported: (File?) -> Unit) = viewModelScope.launch(Dispatchers.IO) {
        try{
            val projection = updateCookiesFile()
            if (projection !is CookieProjectionCoordinator.Outcome.Ready) {
                exported(null)
                return@launch
            }
            val cookieFile = File(projectionContext.cacheDir, "cookies.txt")

            val dir = File("${FileUtil.getCachePath(application)}/Cookie Backups")
            dir.mkdirs()
            val saveFile = File("${dir.absolutePath}/YTDLnisx_Cookies.txt")

            saveFile.delete()
            saveFile.createNewFile()
            cookieFile.copyTo(saveFile, true)

            val res = FileUtil.moveFile(
                saveFile.parentFile!!,
                application,
                FileUtil.getDefaultApplicationPath(),
                false
            ) {}

            exported(File(res[0]))
        }catch (e: Exception){
            e.printStackTrace()
            exported(null)
        }
    }

}

